<?php

$library = [
    [
        'id' => 1,
        'artist' => 'Juice WRLD',
        'title' => 'Armed and Dangerous',
        'genre' => 'hip hop/rap',
        'year' => '2018',
        'image' => '',
    ],
    [
        'id' => 2,
        'artist' => 'Artcic Monkeys',
        'title' => 'R U Mine?',
        'genre' => 'alternative',
        'year' => '2013',
        'image' => '',
    ],
    [
        'id' => 3,
        'artist' => 'Juice WRLD',
        'title' => 'Conversations',
        'genre' => 'hip hop/rap',
        'year' => '2020',
        'image' => '',
    ],
    [
        'id' => 4,
        'artist' => 'Juice WRLD',
        'title' => 'Tell Me U Luv Me',
        'genre' => 'hip hop/rap',
        'year' => '2020',
        'image' => '',
    ],
    [
        'id' => 5,
        'artist' => 'Trippie Redd',
        'title' => 'Matt Hardy 999',
        'genre' => 'hip hop/rap',
        'year' => '2021',
        'image' => '',
    ],
    [
        'id' => 6,
        'artist' => 'XXXTENTACION',
        'title' => 'A GHETTO CHRISTMAS CAROL',
        'genre' => 'hip hop/rap',
        'year' => '2017',
        'image' => '',
    ],
    [
        'id' => 7,
        'artist' => 'Post Malone',
        'title' => 'Better Now',
        'genre' => 'hip hop/rap',
        'year' => '2018',
        'image' => '',
    ],
    [
        'id' => 8,
        'artist' => 'NF',
        'title' => 'LOST',
        'genre' => 'hip hop/rap',
        'year' => '2021',
        'image' => '',
    ],
    [
        'id' => 9,
        'artist' => 'Juice wrld',
        'title' => 'Legends',
        'genre' => 'hip hop/rap',
        'year' => '2018',
        'image' => '',
    ],
    [
        'id' => 10,
        'artist' => 'NLE Choppa',
        'title' => 'Ice Spice',
        'genre' => 'hip hop/rap',
        'year' => '2022',
        'image' => '',
    ],
    [
        'id' => 11,
        'artist' => 'Tyla Yaweh',
        'title' => 'Tommy Lee',
        'genre' => 'Alternative',
        'year' => '2020',
        'image' => '',
    ]
];
